### ISSUE TITLE
Upon Importing an DirectX9 8BIT DDS File, the colors are wrong than what it's supposed to be

### ISSUE THREAD

**Issue by jaigitrep159** [0xC0000054/pdn-ddsfiletype-plus#19] opened 2024-07-25 08:55 UTC
I'm using Paint.NET 5.0.13, with DDSFileTypePlus v1.12.10.

Instead of Blue, the colors are brown. Idk why this happens because of the DDS codec.

(Left: PNG, Right: DDS)
![image](https://github.com/user-attachments/assets/33acb220-b3f8-4e9d-9501-26fdc07db2a6)

[Files.zip](https://github.com/user-attachments/files/16373233/Files.zip) files extracted from MaxHwoy's NFS Binary.

Do you think you can support DX9's TEXCOMP_8BIT and TEXCOMP_8BIT16 codecs?
Thanks.

**Comment by jaigitrep159** [comment] 2024-07-25 09:09
Another one that's similar.

![BMWM3GTRE46_DEBUG](https://github.com/user-attachments/assets/33ddb469-a6db-4394-9beb-383df8b121c3)
Original

![image](https://github.com/user-attachments/assets/7440a447-e413-4685-9c33-de0abc3c2d53)
Paint.NET's DDSFileTypePlus

provided files: [Files2.zip](https://github.com/user-attachments/files/16373430/Files2.zip)

**Comment by jaigitrep159** [comment] 2024-07-25 10:41
It seems like the game texture i extracted from Need for Speed: Most Wanted (2005) Vinyls, is that it uses "DXGI_FORMAT_P8" or "DXGI_FORMAT_A8P8"

according to this doc: https://learn.microsoft.com/en-us/windows/win32/api/dxgiformat/ne-dxgiformat-dxgi_format

it seems like it's a palettized 8 bit image. It also includes alpha.

**Comment by 0xC0000054** [comment] 2024-07-25 11:20
This appears to be an issue with the DirectXTex library that the plugin uses to load DDS files. You will likely get a better answer about what the problem is by opening an issue in the DirectXTex GitHub repository: https://github.com/microsoft/DirectXTex

Looking at the DirectXTex code I couldn't tell if P8 or A8P8 are supported legacy formats.

**Comment by 0xC0000054** [comment] 2024-11-23 09:52
I took another look at this. The issue is the those files have the red and blue channels are swapped in the palette. DirectXTex reads the palette as RGB, which means that the files are using BGR.
Closing as it is not a bug in the plugin.

**Closed as completed by 0xC0000054** 2024-11-23 09:52 UTC
